# -*- coding: utf-8 -*-
"""Rag _Project_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kgldibCIjYjwqMvwpGC4yDCORez37mSq
"""

!pip install -q langchain
!pip install -q langchain-community
!pip install -q langgraph
!pip install -q chromadb
!pip install -q sentence-transformers
!pip install -q langchain-text-splitters
!pip install -q pypdf
!pip install -q transformers
!pip install -q torch

print("Libraries Installed Successfully")


# =========================
# 2. UPLOAD PDF
# =========================

from google.colab import files

uploaded = files.upload()

pdf_file = list(uploaded.keys())[0]

print("Uploaded PDF:", pdf_file)


# =========================
# 3. LOAD PDF
# =========================

from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader(pdf_file)

pages = loader.load_and_split()

documents = pages

print("PDF Loaded Successfully")


# =========================
# 4. SPLIT DOCUMENT
# =========================

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

docs = text_splitter.split_documents(documents)

print("Document Split Successfully")
print("Total Chunks:", len(docs))


# =========================
# 5. CREATE EMBEDDINGS
# =========================

from langchain_community.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

print("Embeddings Created Successfully")


# =========================
# 6. STORE IN CHROMADB
# =========================

from langchain_community.vectorstores import Chroma

vectorstore = Chroma.from_documents(
    documents=docs,
    embedding=embeddings,
    persist_directory="./chroma_db"
)

retriever = vectorstore.as_retriever()

print("ChromaDB Vector Store Ready")


# =========================
# 7. LOAD FREE LLM
# =========================

from transformers import pipeline

generator = pipeline(
    "text2text-generation",
    model="google/flan-t5-base"
)
print("LLM Loaded Successfully")


# =========================
# 8. HITL MODULE
# =========================

def human_support(query):

    return f"""
    HUMAN ESCALATION REQUIRED

    Query:
    {query}

    Forwarded to Human Support Team.
    """


# =========================
# 9. QUERY PROCESSING NODE
# =========================

def process_query(state):

    query = state["query"]

    docs_result = retriever.invoke(query)

    context = "\n".join([
        doc.page_content for doc in docs_result
    ])

    prompt = f"""
    Answer the question only from the given context.

    Context:
    {context}

    Question:
    {query}

    Give short and correct answer.
    """

    response = generator(
        prompt,
        max_new_tokens=100
    )

    answer = response[0]["generated_text"]

    state["context"] = context
    state["answer"] = answer

    return state


# =========================
# 10. CONDITIONAL ROUTING
# =========================

def route_query(state):

    answer = state["answer"].lower()

    escalation_words = [
        "i don't know",
        "not available",
        "cannot answer",
        "no information"
    ]

    if any(word in answer for word in escalation_words):

        state["answer"] = human_support(
            state["query"]
        )

    return state


# =========================
# 11. OUTPUT NODE
# =========================

def output_node(state):

    print("\n==========================")
    print("FINAL RESPONSE")
    print("==========================\n")

    print(state["answer"])

    return state


# =========================
# 12. LANGGRAPH WORKFLOW
# =========================

from typing import TypedDict
from langgraph.graph import StateGraph, END

class GraphState(TypedDict):

    query: str
    context: str
    answer: str


workflow = StateGraph(GraphState)

workflow.add_node(
    "Process_Query",
    process_query
)

workflow.add_node(
    "Route_Query",
    route_query
)

workflow.add_node(
    "Output",
    output_node
)

workflow.set_entry_point(
    "Process_Query"
)

workflow.add_edge(
    "Process_Query",
    "Route_Query"
)

workflow.add_edge(
    "Route_Query",
    "Output"
)

workflow.add_edge(
    "Output",
    END
)

app = workflow.compile()

print("LangGraph Workflow Ready")


query = input("Enter Your Question: ")

result = app.invoke({

    "query": query,
    "context": "",
    "answer": ""

})

print("\nRAG SYSTEM EXECUTED SUCCESSFULLY")

